services:
  backend:
    build: ./server
    container_name: wabot-backend
    ports:
      - "3003:3002"
    volumes:
      - ./server/prisma:/app/prisma
      - ./server/uploads:/app/uploads
      - ./server/sessions:/app/sessions
      - ./server/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=supersecretkeychangedinprod
      - PORT=3002
      - TZ=Asia/Jakarta
    restart: always

  frontend:
    build: ./client
    container_name: wabot-frontend
    ports:
      - "8002:80"
    depends_on:
      - backend
    restart: always
