services:
  backend:
    build: ./server
    container_name: wabot-backend
    ports:
      - "3003:3002"
    volumes:
      - ./server/prisma:/app/prisma
      - ./data/uploads:/app/uploads
      - ./data/sessions:/app/sessions
      - ./data/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3002
      - TZ=Asia/Jakarta
    restart: always
    networks:
      - shared_apps

  frontend:
    build:
      context: ./client
      args:
        VITE_ADMIN_PHONE: "${VITE_ADMIN_PHONE}"
        VITE_ADMIN_EMAIL: "${VITE_ADMIN_EMAIL}"
    container_name: wabot-frontend
    ports:
      - "8002:80"
    depends_on:
      - backend
    restart: always

networks:
  shared_apps:
    external: true
