name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: ./client
      run: npm ci

    - name: Lint Frontend
      working-directory: ./client
      run: npm run lint

    - name: Build Frontend
      working-directory: ./client
      run: npm run build

  backend-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm ci

    - name: Generate Prisma Client
      working-directory: ./server
      run: npx prisma generate

    - name: Run Backend Tests
      working-directory: ./server
      env:
        DATABASE_URL: "file:./test.db"
      run: npm test

  deploy:
    needs: [frontend-build, backend-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: home
    steps:
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.homesislab.my.id
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # ProxyCommand ini yang bertugas 'menyuap' Cloudflare dengan Service Token
          proxy_command: >
            cloudflared access ssh --hostname ssh.homesislab.my.id 
            --cid ${{ secrets.CF_CLIENT_ID }} 
            --csecret ${{ secrets.CF_CLIENT_SECRET }}
          script: |
            cd /home/gie/workspace/wabot
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build
            docker image prune -f

